import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Subject</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <main>
          Initial commit
        </main>
      </Head>
    </div>
  )
}
