import Head from "next/head";
import { useState } from "react";
import Admin from "../components/Admin";
import Subject from "../components/Subject";


export default function Home() {
  const timetable = {
    Monday: ["DAA"],
    Tuesday: ["COMP", "ALC"],
    Wednesday: ["BEE", "OS"],
    Thursday: ["OE", "IT", "DM"],
    Friday: ["DBMS", "S&S"],
  };
  const [data, setData] = useState({});
  const [date, setDate] = useState(new Date().toLocaleDateString("en-GB"));
  const days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];
  const [day, setDay] = useState(days[new Date().getDay()]);
  const [view, setView] = useState("student");

  return (
    <div>
      <Head>
        <title>Subject</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 py-10">
        {view === "student" ? (
          <div className="">
            <h1 className="text-4xl">Student View : </h1>
            <p>Selected Date : {date}</p>
            <p>Day : {day}</p>
            <p>Selected Day&apos;s subjects : {timetable[day].join(", ")}</p>
            <h3>
              Set Date :
              <input
                type={"date"}
                id="date"
                name="date"
                onChange={(e) => {
                  if (e.target.valueAsDate !== null) {
                    setDate(e.target.valueAsDate.toLocaleDateString("en-GB"));
                    setDay(days[e.target.valueAsDate.getDay()]);
                  }
                }}
              />
            </h3>
            {timetable[day].map((e) => (
              <Subject
                key={e}
                name={e}
                data={data}
                setData={setData}
                date={date}
              />
            ))}

            <button
              onClick={() => setView("admin")}
              className="px-4 py-2.5 text-white bg-green-500"
            >
              Admin View
            </button>
          </div>
        ) : (
          <Admin data={data} />
        )}
      </main>
    </div>
  );
}
